apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meow-server
  template:
    metadata:
      labels:
        app: meow-server
    spec:
      containers:
      - name: meow-server
        image: {{ .Values.server.image }}
        ports:
        - containerPort: {{ .Values.server.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: meow-server-svc
spec:
  ports:
  - port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.targetPort }}
    protocol: TCP
  selector:
    app: meow-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meow-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /meow-server
        pathType: Prefix
        backend:
          service:
            name: meow-server-svc
            port:
              number: {{ .Values.server.port }}
  {{ if .Values.server.port }}
  tls:
  - secretName: {{ .Values.server.secretname }}
  {{ end }}
