apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meow-client
  template:
    metadata:
      labels:
        app: meow-client
    spec:
      containers:
      - name: meow-client
        image: {{ .Values.client.image }}
        env:
          - name: GRPC_SERVER_ADDRESS
            value: {{ .Values.server.path }}
        ports:
        - containerPort: {{ .Values.client.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: meow-client-svc
spec:
  ports:
  - port: {{ .Values.client.port }}
    targetPort: {{ .Values.client.targetPort }}
    protocol: TCP
  selector:
    app: meow-client
---
apiVersion: v1
kind: Service
metadata:
  name: meow-client-rest-svc
spec:
  ports:
  - port: {{ .Values.client.rest.port }}
    targetPort: {{ .Values.client.rest.targetPort }}
    protocol: TCP
  selector:
    app: meow-client
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meow-client-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /meow
        pathType: Prefix
        backend:
          service:
            name: meow-client-rest-svc
            port:
              number: {{ .Values.client.rest.port }}
