client:
  image: "meow-client:1.0"
  targetPort: 5001
  port: 5001
  rest:
    targetPort: 5002
    port: 5002

server:
  image: "meow-server:1.0"
  targetPort: 5001
  port: 5001
  path: localhost:443/meow-server
  secretname: grpc-secret
